version: '3.8'

services:
  # Tambahkan Service Database
  mongo:
    image: mongo:latest
    container_name: pmate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: pmate-backend
    ports:
      - "3000:3000"
    environment:
      # Backend akan connect ke hostname 'mongo' (sesuai nama service di atas)
      - MONGO_URI=mongodb://mongo:27017/pmate_db 
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: pmate-frontend
    ports:
      - "80:80" # Nginx
      - "5173:5173" # Vite Dev (opsional jika development)
    depends_on:
      - backend

volumes:
  mongo-data: